### ISSUE TITLE
Question: What is the best way to integrate the adapter with the Firebase performance monitoring

### ISSUE THREAD

**Issue by juviwhale** [mikkopaderes/ember-cloud-firestore-adapter#111]
We have an existing ember app using the adapter and we added Firebase’s ‘newish’ [performance monitoring service](https://firebase.google.com/docs/perf-mon).  The drop-in http profiling is very limited and groups all of our Firestore queries into one big bucket. 

What would you recommend as the best approach to capturing more fine grained custom traces of Firestore interactions made through your adapter? Any tips or generally direction is greatly appreciated.

**Comment by mikkopaderes** [comment]
This library is very specific for Cloud Firestore but this also uses [`ember-firebase-service`](https://github.com/mikkopaderes/ember-firebase-service). You can follow the configuration steps there in order to add `firebase-performance` then it will be available in `firebase` service as `this.firebase.performance()`.
