### ISSUE TITLE
Emulator warnings in tests due to instance-initializer

### ISSUE THREAD

**Issue by charlesfries** [mikkopaderes/ember-cloud-firestore-adapter#197]
I'm seeing this browser warning dozens of times while 1) using the emulator, and 2) running tests in the qunit UI (`localhost:4200/tests`, not `ember test`, the warning doesn't appear in the latter).

```
@firebase/firestore: Firestore (9.1.1): Host has been set in both settings() and useEmulator(), emulator host will be used
```

Believe this is because the `firebase-settings` instance initializer is recreated for each test but the overall state is shared. Is the solution turning the `firebase-settings` instance initializer into a standard initializer?

Repro:

```
ember new my-app &&
cd my-app &&
ember install ember-simple-auth ember-cloud-firestore-adapter firebase &&
ember g adapter application &&
ember g serializer application &&
firebase init
```

`standard config, adapter, serializer`

```diff
// package.json

- "start": "ember serve",
+ "start": "firebase emulators:exec \"ember serve\"",
```

```
npm start
http://localhost:4200/tests
```

**Comment by mikkopaderes** [comment]
Yes, you're right. It's because of the instance initializer. However, I don't think I can move to standard initializer as I don't think it has access to the `config:environment` at that point. I think that once we move to modular SDK, this warnings will be gone (although I may be wrong).

For now, it's not a big issue as it's only visible in local development. The issue won't happen in production.
